name: Release Java tring
on:
  push:
    tags:
      - 'tringapi-*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Setup Java and Apache Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'
        server-id: gluon-nexus
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
    - name: Release Tring API
      run: |
        cd src/java/tringapi
        mvn -ntp deploy
      env:
        MAVEN_USERNAME: ${{ secrets.GLUON_NEXUS_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.GLUON_NEXUS_PASSWORD }}
